### ISSUE TITLE
Advice on API design

### ISSUE THREAD

**Issue by rajzru** [ptboyer/restful-api-design-tips#2]
I want to understand the best practices that we need to consider while designing API responses.

**Problem Statement**

Let's assume I have an endpoint /v1/projects/all which return the list of projects and its response look something like this

```
{
    "projects": [{
        "id": "001",
        "name": "test nw UPM member",
        "isPublic": false,
        "isShared": false,
    }, {
        "id": "002",
        "name": "move test",
        "isPublic": false,
        "isShared": true,
    }]
}

```

Notice the `isShared` flag indicates if the project is shared with other users. If it is

true - It means the project is shared with another user
false - It means the project is not shared with another user

Now I have another API that only gives me the list of shared projects

The endpoint looks something like this /v1/projects/shared-by-me The response of that looks like below

```
{
    "projects": [{
        "id": "002",
        "name": "move test",
        "isPublic": false,
    }]
}
```

Note: I do not pass `isShared` flag here since the endpoint itself indicates that projects are shared by me meaning `isShared` will be always true in that case.

**Question**

What according to best practices should the response be like? Should I include the `isShared` property in `/v1/projects/shared-by-me` or it's ok to not include that?

**Client Side Implementation**

Assume client side has a common react component that renders the details based on this response. so If I don't pass `isShared` it is recommended for Client-side to add it manually and add conditional redering?

**Comment by peterboyer** [comment]
Hi @rajzru, thanks for the question!

Firstly, I'd like to start with your hypothetical endpoint: `/v1/projects/all`.

As I write [here](https://github.com/ptboyer/restful-api-design-tips#use-plurals), when creating your endpoints, you shouldn't specify `/all` because the collection of `/projects` (as a plural) implies that you are querying "all" projects from that endpoint, and instead of `/all` you would instead provide an `/:id` to select a particular "Project" entity from the resource collection of `/projects`.

Think of this pattern as `/edge/node/edge/node/.../...` where each `edge` is a relationship/collection, and the `node` is the specific item inside that collection. That's what I write [here](https://github.com/ptboyer/restful-api-design-tips#use-nesting-for-relationship-filtering) about using the URL as a means of filtering by relationship/edge.

Now with this idea of `/edge/node/...` let's take your example of the endpoint `/v1/projects/shared-by-me`. This is similar to the case of `/all`, where `/shared-by-me` is expressing the `edge` between a user and many projects, but unfortunately breaks the `/edge/node/edge/...` pattern, with `/projects(edge)/shared-by-me(edge)`.

There is a better/cleaner way to address this.

In this API I imagine that a `User` entity may be exposed via `/users/:id`, or via `/me` (as I [hint with here](https://github.com/ptboyer/restful-api-design-tips#use-the-authorisation-context-to-filter)) providing an endpoint to target yourself as a `User` node. This node can have many `edges` (relationships), as following the pattern earlier `/node/edge` i.e. to be able to express your project relationship above as either:
- (1) `/me/shared-projects`, or even
- (2) `/me/projects?shared`.

It's really up to you as to whether you want to express the relationship as a dedicated `edge` for projects filtered as shared relative to you (1), OR as a general projects edge that accepts query params (2). Either of these options is preferable over abitrarily using the URL to filter filter filter `edges` without any `nodes`.

To now address your main question: "Should I include the isShared property in /v1/projects/shared-by-me or it's ok to not include that?"

In the case of any API, **the structure of the entities that you expose must be consistent** for the user who accesses them.

You have one endpoint `/projects` that provides a `isShared` field for a Project entity, whereas another endpoint `/projects/shared-by-me` does not provide this field, despite BOTH endpoints exposing a "Project" entity. **This is not ideal.**

**With REST APIs you should return the entire entity object consistently everywhere that that entity is exposed.**

Unfortunately this technically means returning all fields even if the consumer doesn't need them all (which is what GraphQL solves). Similar to Graph, you _could_ create a `?fields=id,name,etc...` query param on all `node` endpoints to allow you to select only the fields that you need, although at that point you may want to consider using GraphQL (if you can).

To further expand on my `/edge/node/...` concept earlier: you present two entity concepts `User` and `Project` which might have properties (attributes) and edges (relationships).

```
User {
  id
  sharedProjects  --- EDGE, expressing a relationship
}
Project {
  id
  name
  isPublic
  isShared
}
```

To access these entities we have ROOT `edges` of the api, such as `/projects` (which returns all projects, and their attributes (but not edges) from which we can target a `node`, such as `/projects/123` (which returns only project `123` attributes (and no edges).

Then if we want to explore those `edges` instrinsic to that Project `node` we can use `/projects/123/comments`, or in the case of a User accessing their own shared projects `/users/321/shared-projects` or `/me/shared-projects`. And if we want to `GET` a project from `/me/shared-projects` we could either `/me/shared-projects/123` or `/projects/123`.

Although for mutating a Project (or any entity for that matter), I would only allow that via a root `edge` such as `POST /projects/123` and NOT `/me/shared-projects/123` as I write [here](https://github.com/ptboyer/restful-api-design-tips#use-more-of-your-route-space) about using your route space and only using nested resource paths for GET/reading entities by edges/relationships only.

I hope that helps you with your question. :) Let me know if you have any more questions, I'll be happy to answer them!

As you may tell, I'm shifting to use more Graph related terms like `edge` and `node` as I have been using GraphQL extensively recently.

Cheers!

**Comment by peterboyer** [comment]
Oh, and I missed this one: _"Assume client side has a common react component that renders the details based on this response. so If I don't pass isShared it is recommended for Client-side to add it manually and add conditional redering?"_

As I say above, you should be returning `isShared` also. Although depending on whether or not you decide to provide some kind of `?fields=` query param, if your component _needs_ that common information then your API should give it to you or you conditionally (and gracefully) handle its absence. :)

**Comment by rajzru** [comment]
Thank you for the clarification and its great insights. It helps a lot.
